---
kind: Service
apiVersion: v1
metadata:
  name: capstoneservice
spec:
  selector:
    app: myapp
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 80
      # Port to forward to inside the pod
      targetPort: 8080
  type: LoadBalancer



---
apiVersion:  apps/v1
kind: Deployment
metadata:
  name: myappdeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: newthingade/dockerhub:capstone-project
          ports:
            - containerPort: 8080